[window_mode]
width = 1280.0
height = 800.0
maximized = false
fullscreen_type = "Windowed"
borderless = false
transparent = false
min_width = 1.0
min_height = 1.0
max_width = 0.0
max_height = 0.0
resizable = false
visible = true
resize_on_scale_factor_change = false

[window_setup]
title = "OpenMoonstone"
samples = "One"
vsync = true
icon = ""
srgb = true

[backend]
type = "All"
